### ISSUE TITLE
New Discord image URLs don't work in the API

### ISSUE THREAD

**Issue by BreadBreadington** [jacebrowning/memegen#843] opened 2024-02-22 05:16 UTC
Recently Discord has implemented a change to uploaded images that make them expire. They now have a few URL parameters, "ex", "is", and "hm"

Example: https://cdn.discordapp.com/attachments/757770251390812190/1210087514778370048/stare.png?ex=65e948d1&is=65d6d3d1&hm=3dd6ac163b71acc90cf4d4269325af966067d888bdcebc014ed5bb918b80c066&

Whenever one of these URLs is passed through the API it'll fail and return the placeholder background

Example: https://api.memegen.link/images/custom/_/my_background.png?background=https://cdn.discordapp.com/attachments/757770251390812190/1210087514778370048/stare.png?ex=65e948d1&is=65d6d3d1&hm=3dd6ac163b71acc90cf4d4269325af966067d888bdcebc014ed5bb918b80c066&

Same result when trying without the URL parameters. 

I have noticed that if you try to make a meme through the [website](https://memecomplete.com/custom/), the preview will look as expected but the generated image will have the same problem

**Comment by jacebrowning** [comment] 2024-02-22 16:17
It looks like we will need to escape additional query parameters in custom background image URLs, like this: 

https://api.memegen.link/images/custom/_/my_background.png?background=https://cdn.discordapp.com/attachments/757770251390812190/1210087514778370048/stare.png%3Fex=65e948d1%26is=65d6d3d1%26hm=3dd6ac163b71acc90cf4d4269325af966067d888bdcebc014ed5bb918b80c066

**Comment by jacebrowning** [comment] 2024-02-23 23:36
The `/images/custom` API should now escape query parameters in custom background image URLs.

Let me know if you run into this issue anywhere else!

**Comment by jacebrowning** [comment] 2024-02-23 23:40
Actually, I see that https://memecomplete.com/custom/ (an API client) may still not be working with Discord links. I'll look into that...

**Comment by jacebrowning** [comment] 2024-02-24 23:30
OK, this should be fixed for all API clients.

**Closed by jacebrowning** 2024-02-24 23:30 UTC
Labels: bug, backend

**Comment by BreadBreadington** [comment] 2024-02-25 03:39
Working nicely. Thanks for the quick turnaround

**Comment by HumanBot000** [comment] 2024-03-17 07:41
For me the /images/custom endpoint doesn't work 

For example

https://api.memegen.link/images/custom/%7Bmeme_text%7D/_/my_background.png?background=https://cdn.discordapp.com/attachments/1082684758380781651/1218672791067295844/meme.png?ex=6608847b&is=65f60f7b&hm=91240681812a67ed0dd3568bf5e6fe219b78995928010cb0fa7a46001b5d57d8&


Returns a placeholder image

**Comment by jacebrowning** [comment] 2024-03-20 00:10
@HumanBot000 can you share the parameters you sent to the `/images/custom` API endpoint? Sharing the generated `curl` command from https://api.memegen.link/docs#/Images/post~Images.create_custom would be helpful.

**Comment by BreadBreadington** [comment] 2024-03-20 02:20
I suspect it's due to yet another change to discord that's broken it again. This time I don't think there's an easy fix.

If you try to use a discord image URL with the ex, is, and hm parameters outside of discord and after the image has expired, it won't work unless you post the URL inside discord, where discord will then request the image again from their CDN with an updated expiry time.

Hopefully the Discord API implements a way to request a new URL, but I'm not holding my breath. One solution to this could be fetching the Discord message by its ID and then getting the URL that way, but I haven't tried this out, and I doubt it's much good for most use cases

**Comment by HumanBot000** [comment] 2024-03-20 07:31
But the image isn't expired when I generate the meme image. This should only be a problem when I wait for to long, what I am not doing. I will try it with the id

**Comment by HumanBot000** [comment] 2024-03-23 14:37
> I suspect it's due to yet another change to discord that's broken it again. This time I don't think there's an easy fix.
> 
> If you try to use a discord image URL with the ex, is, and hm parameters outside of discord and after the image has expired, it won't work unless you post the URL inside discord, where discord will then request the image again from their CDN with an updated expiry time/signature.
> 
> Hopefully the Discord API implements a way to request a new URL, but I'm not holding my breath. One workaround for @HumanBot000 could be fetching the Discord message by its ID and then getting the URL that way, but I haven't tried this out, and I doubt it's much good for most use cases



What exactly do you mean? Build an own URL? I don't think this is going to work because I can't just build a link like 
https://cdn.discordapp.com/attachments/{channel_id}/{msg_id}/{filename} 

without the is,ex and hm because discords cdn says image is not available without these params.

**Comment by HumanBot000** [comment] 2024-03-24 18:44
@BreadBreadington

**Comment by HumanBot000** [comment] 2024-03-24 18:44
?

**Comment by HumanBot000** [comment] 2024-04-01 16:12
> @HumanBot000 can you share the parameters you sent to the `/images/custom` API endpoint? Sharing the generated `curl` command from https://api.memegen.link/docs#/Images/post~Images.create_custom would be helpful.

I just use a get request without any extra parameters just the background text and the discord can url.

**Comment by HumanBot000** [comment] 2024-04-01 16:12
> @HumanBot000 can you share the parameters you sent to the `/images/custom` API endpoint? Sharing the generated `curl` command from https://api.memegen.link/docs#/Images/post~Images.create_custom would be helpful.

I just use a get request without any extra parameters just the background text and the discord can url.

**Comment by HumanBot000** [comment] 2024-04-07 13:17
> > @HumanBot000 can you share the parameters you sent to the `/images/custom` API endpoint? Sharing the generated `curl` command from https://api.memegen.link/docs#/Images/post~Images.create_custom would be helpful.
> 
> I just use a get request without any extra parameters just the background text and the discord can url.

@jacebrowning

**Comment by HumanBot000** [comment] 2024-04-14 15:53
@jacebrowning here is the curl


curl -X GET -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'User-Agent: python-requests/2.31.0' 'https://api.memegen.link/images/custom/_'"'"''"'"'When_you'"'"'re_trying_to_learn_a_new_language_but_the_app_keeps_crashing.'"'"''"'"'/_/my_background.png?background=https://cdn.discordapp.com/attachments/1082684758380781651/1229096907343794256/meme.png%3Fex%3D662e70b2&is=661bfbb2&hm=6c970161c84edd691c3a59d7df5980f00c05828efd71bdc123f2c92d8992dcfc'

**Comment by robert-huang** [comment] 2024-06-17 04:39
i'm seeing something similar happen to media-amazon urls - it contains some quality/sizing parameters in the url and then it fails to load as a custom overlay 
https://api.memegen.link/images/pigeon/Engineer/_/Is_this_Photoshop~q.png?style=https://m.media-amazon.com/images/I/71XOupccufL._UF1000,1000_QL80_.jpg
the image itself loads properly https://m.media-amazon.com/images/I/71XOupccufL._UF1000,1000_QL80_.jpg

the weird thing is if i remove the extra parameters in the url, then it retrieves the original image and that one works as an overlay if i put it into the url
https://api.memegen.link/images/pigeon/Engineer/_/Is_this_Photoshop~q.png?style=https://m.media-amazon.com/images/I/71XOupccufL.jpg

**Comment by HumanBot000** [comment] 2024-07-30 20:32
What's the state of this issue? The problem isn't fixed. Why is it closed.

**Comment by HumanBot000** [comment] 2024-08-02 16:48
@jacebrowning
