### ISSUE TITLE
Browse Images like a Gallery

### ISSUE THREAD

**Issue by dargrall** [jacebrowning/memegen#723] opened 2022-07-05 05:56 UTC
Is it possible to browse all available templates like a gallery on your phone? Didn't find a way to do it yet and it's kind of exhausting to try finding the right meme by clicking through all the template folders and looking at the images

**Comment by jacebrowning** [comment] 2022-07-05 21:18
I think this is a duplicate of https://github.com/jacebrowning/memegen/issues/664. Please comment there for additional discussion.

**Closed by jacebrowning** 2022-07-05 21:18 UTC
