### ISSUE TITLE
Discord Image URLs result in Placeholder Image on custom Text endpoint

### ISSUE THREAD

**Issue by HumanBot000** [jacebrowning/memegen#849] opened 2024-03-16 21:34 UTC
For Example https://api.memegen.link/images/custom/%7Bmeme_text%7D/_/my_background.png?background=https://cdn.discordapp.com/attachments/1082684758380781651/1218672791067295844/meme.png?ex=6608847b&is=65f60f7b&hm=91240681812a67ed0dd3568bf5e6fe219b78995928010cb0fa7a46001b5d57d8&

Results in a weird Placeholder image with the Text.  But the discord image CDN URL is accessible for public (from any browser). SO it isn't encrypted or Something.

**Comment by jacebrowning** [comment] 2024-03-17 02:34
Is this related to https://github.com/jacebrowning/memegen/issues/843?

**Comment by HumanBot000** [comment] 2024-03-17 07:34
Yes I think it is. I think the API is treating the query params like ex as query parameters of the API url and not the discord image

**Comment by HumanBot000** [comment] 2024-03-17 15:14
But the other Issue says, that the issue is fixed. For me it isn't

**Comment by HumanBot000** [comment] 2024-03-18 15:18
@jacebrowning ?

**Comment by jacebrowning** [comment] 2024-03-20 00:08
Duplicate of #843

**Closed by jacebrowning** 2024-03-20 00:08 UTC
